### ISSUE TITLE
Sync an Asana task and Github issue

### ISSUE THREAD

**Issue by caseypugh** [jamieforrest/github-asana#5]
I use a Asana for high-level project management, but sometimes there are very specific tasks mixed in that are usually converted into a Github issues. This basically duplicates our tasks since we have to close the task in both github and in asana.

It would be great if there was a way to selectively turn an Asana task into a Github issue, effectively merging the two together (or syncing them). If you comment on asana, it will comment on github. If you comment on github, it will comment on asana. If you check it on Asana, it will close the issue on Github.

**Comment by jmny** [comment]
+1

**Comment by ivanbreet** [comment]
+1

**Comment by jamieforrest** [comment]
This is really not an issue but a request for an entirely different type of system. This app is intended for the use case of sending notes from git commits to Asana, not providing a full synchronization of Asana tasks and Github issues.

**Comment by caseypugh** [comment]
:'(

**Comment by maxheld83** [comment]
+1 ?

**Comment by KyleChamberlin** [comment]
Is there any chance this could be implemented through another app? I know the author mentioned it is out of scope for this project, but I am hoping there is some chance of this integration in another app. anyone know of a place to look for this?

**Comment by khashayar** [comment]
@KyleChamberlin You can achieve it by [Zapier](https://zapier.com/zapbook/asana/github/)

**Comment by KyleChamberlin** [comment]
Zapier is fine, I tried that about a year ago, in order to setup syncing on multilpe repors you need a sync task (or Zap) for github->asana and a second zap for asana->github and those are just for opening new tasks. that worked ok, but it doesn't sync closing of issues/tasks. i also belive that when I looked at it, there was no way to close issues/tasks with zapier. but that would require two more tasks (zaps) and lastly another feature that would seem to be missing in that solution is the ability to sync comments between the platforms (similar to what waffle.io does) which would require two further zaps. so that would leave me with six zaps per repository (assuming you would want the issues from different repos sync'ed to different asana projects.) given the fact that zapier charges per zap and per use, that would get expensive quickly.

**Comment by marcboscher** [comment]
@KyleChamberlin @caseypugh I had the same requirement to use Asana to interface with GitHub. Build a tool to sync both, tasks and comments included. Might work for you too: https://github.com/marcboscher/crosscheck

It's still rough, but I use it every day. Let me know what you think.

It's also packaged as a Chrome extension with other Asana power user goodies.
https://chrome.google.com/webstore/detail/crosscheck-for-asana/cbnanllnipdggjajbdceeglkiahlknfg

**Comment by soundofjw** [comment]
@KyleChamberlin @marcboscher @caseypugh 
Likewise, here's another tool written in python designed to accomplish the same task:
https://github.com/Loudr/asana-hub

`crosscheck` looks pretty sweet too!

**Comment by AlokBansal8** [comment]
To make Asana more friendlier, we need complete synchronisation of asana tasks and github issues.

**Comment by marcboscher** [comment]
@AlokBansal8 have a look at http://unito.io, does 2-way sync of Asana-GitHub, including comments, assignees, tabs/labels

**Comment by sahin** [comment]
@marcboscher I just did my first sync with chrome extenstion, it is great.

I have few question

1) what is the diff btw unito.io vs crosscheck.io
2) How can I map github users to asana users?

**Comment by marcboscher** [comment]
@sahin Unito is the rebrand and evolution of CrossCheck, same team, more features, including user and tag sync

**Comment by sethherr** [comment]
@marcboscher :+1: - just signed up for Unito, and it has some rough edges - but it's exactly what I'm looking for, thank you!

**Comment by marcboscher** [comment]
@sethherr awesome! Let me know which edges are the roughest, and we'll pull out the iron!

**Comment by carl-alberto** [comment]
+1

**Comment by marcboscher** [comment]
@carl-alberto https://asana.com/apps/github

**Comment by guruprasad83** [comment]
I tried using Unito which works great in bidirectional. But the issue is the commentor name in GIT appears always as the Repository owner. Unito had mentioned this saying its the behavior of the current verion. But wanted to know, any solution for this in Unito ? or any light on this issue please?

**Comment by marcboscher** [comment]
@guruprasad83 that's because you are using the repository owner as the sync account.  You can use a dedicated sync account to make things more intuitive. Details here:

https://guide.unito.io/hc/en-us/articles/215108108-Why-do-I-get-my-name-on-all-comments-

Also, our upcoming platform revamp will support comments made on behalf of the original author. Stay tuned!

**Comment by guruprasad83** [comment]
@marcboscher thanks for the quick response. much appreciated.

**Comment by uncannyken** [comment]
Is there any way to do this without having to pay for an extra user account for the bot on the tools we want to integrate with Unito?  I'm looking specifically at Asana and Github.
